# [9665] Neural Network

In [ ]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 03/24/25 13:06:54


### Import libraries

In [ ]:
import numpy as np

### Seed random numbers to make calculations deterministic

In [ ]:
np.random.seed(1)

### Create a nonlinear activation function (sigmoid)

In [ ]:
def nonlin(x, deriv=False):
    if (deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

## Part 1 - linearly separable problem (1-layer neural network)
Predict the output column given the three input columns. We could solve this problem by simply measuring statistics between the input values and the output values. If we did so, we would see that the leftmost input column is perfectly correlated with the output. Backpropagation, in its simplest form, measures statistics like this to make a model.

### Load data

In [ ]:
# Create input data
X = np.array([ [0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1] ])

In [ ]:
# Create output data
y = np.array([[0,0,1,1]]).T

### Review data

In [ ]:
X.shape

(4, 3)

In [ ]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
y.shape

(4, 1)

In [ ]:
y

array([[0],
       [0],
       [1],
       [1]])

### Train 1-layer neural network

X : input (independent) data  
y : target (dependent) data  
L0 : input layer  
No hidden layer  
L1 : output layer  
syn0 : synapse 0 : set of weights connecting L0 to L1  
L1_error : the error of the prediction after each iteration

In [ ]:
# Seed weight matrix for input layer to output layer
#  Initialize weights randomly
#   We need 3 weights because we have 3 input neurons (features)
#    connecting to 1 output neuron
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:
%%time

NUM_ITERATIONS = 100000
for iter in range(NUM_ITERATIONS):

    # forward propagation
    L0 = X
    L1 = nonlin(np.dot(L0, syn0))

    # calculate error
    L1_error = y - L1

    if (iter % 10000) == 0:
        print(f'Prediction error = {str(np.mean(np.abs(L1_error)))} after {iter} iterations')

    # backpropagation
    #  multiply the error by the slope of the sigmoid for the values in L1
    L1_delta = L1_error * nonlin(L1, True)

    # update weights
    syn0 += np.dot(L0.T, L1_delta)

Prediction error = 0.5172082754380926 after 0 iterations
Prediction error = 0.007954845066726928 after 10000 iterations
Prediction error = 0.005597823963397232 after 20000 iterations
Prediction error = 0.004560869180125656 after 30000 iterations
Prediction error = 0.0039448224333886225 after 40000 iterations
Prediction error = 0.0035253088374209004 after 50000 iterations
Prediction error = 0.0032161023467348754 after 60000 iterations
Prediction error = 0.002976059685215424 after 70000 iterations
Prediction error = 0.002782740030219482 after 80000 iterations
Prediction error = 0.002622727392698709 after 90000 iterations
CPU times: user 2.53 s, sys: 118 ms, total: 2.65 s
Wall time: 4.74 s


Note: The prediction error decreases as # of iterations increases

### Evaluate 1-layer neural network

In [ ]:
print(f'Predicted values:\n\t{L1.T}')
print(f'Actual values:\n\t{y.T}')

Predicted values:
	[[0.00301758 0.00246109 0.99799161 0.99753723]]
Actual values:
	[[0 0 1 1]]


Note: Predictions look pretty good

## Part 2 - nonlinearly separable problem (1-layer neural network)

### Load data

Use same input data from Part 1  
Change output data to represent the XOR problem

In [ ]:
# Create different output data
y = np.array( [ [0],[1],[1],[0] ] )

### Review data

In [ ]:
y.shape

(4, 1)

In [ ]:
y

array([[0],
       [1],
       [1],
       [0]])

#### Use same nonlinear activation function (sigmoid) as in Part 1

### Train 1-layer neural network

X : input (independent) data  
y : target (dependent) data  
L0 : input layer  
No hidden layer  
L1 : output layer  
syn0 : synapse 0 : set of weights connecting L0 to L1  
L1_error : the error of the prediction after each iteration

In [ ]:
# Seed weight matrix for input layer to output layer
#  Initialize weights randomly
#   We need 3 weights because we have 3 input neurons (features)
#    connecting to 1 output neuron
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.39533485],
       [-0.70648822],
       [-0.81532281]])

In [ ]:
%%time

NUM_ITERATIONS = 100000
for iter in range(NUM_ITERATIONS):

    # forward propagation
    L0 = X
    L1 = nonlin(np.dot(L0, syn0))

    # calculate error
    L1_error = y - L1

    if (iter % 10000) == 0:
        print(f'Prediction error = {str(np.mean(np.abs(L1_error)))} after {iter} iterations')

    # backpropagation
    #  multiply the error by the slope of the sigmoid for the values in L1
    L1_delta = L1_error * nonlin(L1, True)

    # update weights
    syn0 += np.dot(L0.T, L1_delta)

Prediction error = 0.5065394693955594 after 0 iterations
Prediction error = 0.5 after 10000 iterations
Prediction error = 0.5 after 20000 iterations
Prediction error = 0.5 after 30000 iterations
Prediction error = 0.5 after 40000 iterations
Prediction error = 0.5 after 50000 iterations
Prediction error = 0.5 after 60000 iterations
Prediction error = 0.5 after 70000 iterations
Prediction error = 0.5 after 80000 iterations
Prediction error = 0.5 after 90000 iterations
CPU times: user 2.56 s, sys: 89.9 ms, total: 2.65 s
Wall time: 5.64 s


Note: The prediction error stalls at 50%

A 1-layer neural network cannot solve this nonlinearly separable problem

## Part 3 - nonlinearly separable problem (2-layer neural network)

Use same input data from Parts 1 & 2  
Use same output data from Part 2  
Use same nonlinear activation function (sigmoid) from Parts 1 & 2

### Train 2-layer neural network (with 1 hidden layer)

X : input (independent) data  
y : target (dependent) data  
L0 : input layer  
L1 : hidden layer 1  
L2 : output layer  
syn0 : synapse 0 : set of weights connecting L0 to L1  
syn1 : synapse 1 : set of weights connecting L1 to L2  
L2_error : the error of the prediction on each iteration

In [ ]:
# Seed weight matrix for input layer to hidden layer
#  Initialize weights randomly
#   We need 12 weights because we have 3 input neurons (features)
#    connecting to 4 hidden neurons
#    Note: We could have chosen more or fewer hidden neurons
syn0 = 2*np.random.random((3,4)) - 1
syn0

array([[-0.62747958, -0.30887855, -0.20646505,  0.07763347],
       [-0.16161097,  0.370439  , -0.5910955 ,  0.75623487],
       [-0.94522481,  0.34093502, -0.1653904 ,  0.11737966]])

In [ ]:
# Seed weight matrix for hidden layer to output layer
#  Initialize weights randomly
#   We need 4 weights because we have 4 hidden neurons
#    connecting to 1 output neuron
syn1 = 2*np.random.random((4,1)) - 1
syn1

array([[-0.71922612],
       [-0.60379702],
       [ 0.60148914],
       [ 0.93652315]])

In [ ]:
%%time

NUM_ITERATIONS = 100000
for iter in range(NUM_ITERATIONS):

    # forward propagation
    L0 = X
    L1 = nonlin(np.dot(L0, syn0))
    L2 = nonlin(np.dot(L1, syn1))

    # calculate error
    L2_error = y - L2

    if (iter % 10000) == 0:
        print(f'Prediction error = {str(np.mean(np.abs(L2_error)))} after {iter} iterations')

    # in what direction is the target value?
    L2_delta = L2_error * nonlin(L2, deriv=True)

    # start of backpropagation

    # how much did each L1 value contribute to the L2 error (according to the weights)?
    L1_error = L2_delta.dot(syn1.T)

    # in what direction is the target L1?
    L1_delta = L1_error * nonlin(L1, deriv=True)

    # end of backpropagation

    # update weights
    syn1 += L1.T.dot(L2_delta)
    syn0 += L0.T.dot(L1_delta)

Prediction error = 0.4994301178104692 after 0 iterations
Prediction error = 0.011989835996651769 after 10000 iterations
Prediction error = 0.008142001318052771 after 20000 iterations
Prediction error = 0.006522785496207261 after 30000 iterations
Prediction error = 0.005581202329061755 after 40000 iterations
Prediction error = 0.004948732805486246 after 50000 iterations
Prediction error = 0.004487176357044975 after 60000 iterations
Prediction error = 0.004131626210418432 after 70000 iterations
Prediction error = 0.003847085734395803 after 80000 iterations
Prediction error = 0.003612819135859126 after 90000 iterations
CPU times: user 4.48 s, sys: 58.7 ms, total: 4.54 s
Wall time: 5.14 s


Note: With a 2-layer neural network, the prediction error decreases as the # of iterations increases

### Evaluate 2-layer neural network (with 1 hidden layer)

In [ ]:
print(f'Predicted values:\n\t{L2.T}')
print(f'Actual values:\n\t{y.T}')

Predicted values:
	[[0.00175579 0.99634507 0.9963069  0.00455891]]
Actual values:
	[[0 1 1 0]]


Note: Predictions look pretty good